apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ../kompose convert -f ../daliserv/docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
    'kompose.volume.size: 2Gi': ""
    traefik.enable: "true"
    traefik.http.routers.freeloader.rule: PathPrefix(`/freeloader`)
    traefik.http.services.freeloader.loadbalancer.server.port: "8070"
  creationTimestamp: null
  labels:
    io.kompose.service: freeloader
  name: freeloader
spec:
  ports:
    - name: "8070"
      port: 8070
      targetPort: 8070
  selector:
    io.kompose.service: freeloader
status:
  loadBalancer: {}
