apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert -f ../daliserv/docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: schedman
  name: schedman
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: schedman
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ../kompose convert -f ../daliserv/docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/daliserv-default: "true"
        io.kompose.service: schedman
    spec:
      containers:
        - env:
            - name: APP_HOST
              value: freeloader:8070
            - name: REDIS_HOST
              value: redis
            - name: TZ
              value: America/New_York
          image: gwyncm/schedman:24.01.19
          name: schedman
          ports:
            - containerPort: 8060
              hostPort: 8060
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
