apiVersion: v1
kind: Service
metadata:
  name: {{ include "dalichart.fullname" . }}-schedman
  labels:
    io.kompose.service: schedman
  {{- include "dalichart.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: ../kompose convert -f ../daliserv/docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
spec:
  type: {{ .Values.schedman.type }}
  selector:
    io.kompose.service: schedman
  {{- include "dalichart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.schedman.ports | toYaml | nindent 2 -}}