apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dalichart.fullname" . }}-uploads-vol
  labels:
    io.kompose.service: uploads-vol
  {{- include "dalichart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.uploadsVol.storageRequest | quote }}