version: '3.6'

services:

  traefik:
    image: traefik:v2.11
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "8080:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8085:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
   
  freeloader:
    image: gwyncm/freeloader:24.02.20
    ports:
      - 8070:8070    
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      TZ: 'America/New_York'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freeloader.rule=PathPrefix(`/freeloader`)"
      - "traefik.http.services.freeloader.loadbalancer.server.port=8070"
      - "kompose.volume.size: 2Gi"
    volumes:
      -  ./uploads:/freeloader/uploads
    restart: always

  daliapp:
    image: gwyncm/daliapp:24.03.12
    depends_on:
      - redis
      - freeloader
    deploy:
      replicas: 1
    environment:
      REDIS_HOST: redis
      APP_HOST: daliapp:8090
      TZ: 'America/New_York'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.daliapp.rule=PathPrefix(`/daliapp`)"
      - "traefik.http.services.daliapp.loadbalancer.server.port=8090"
    volumes:
      -  ./uploads:/daliapp/uploads
    restart: always

  redis:
    image: redis:6.2-bookworm
    ports: 
      - 6379:6379
    volumes:
      - redis_vol:/data
    restart: always

  daliserv:
    image: gwyncm/daliserv:24.03.12
    depends_on:
      - redis
      - daliapp
    deploy:
      replicas: 2
    environment:
      REDIS_HOST: redis
      APP_HOST: daliapp:8090
    restart: always

volumes:
  redis_vol: